name: Demo pipeline

on:
    push:
        branches:
            -main
            -dev
    pull_request:
        branches: [main, dev]   
    schedule:
        - cron: "*/1 * * * *"  

jobs:
    
    setup_job:
        runs-on: ubuntu-latest # macos-latest , window-latest
        steps:
            - name: Checkout repo
              uses:  actions/checkout@0ad4f3bde3aeedc7f5efc6c2f6cb3bc86f21d0f3
            - name: create file
              run: touch github-action.txt
            - name: print hello world
              run: echo Hello world
            - name: display readme file
              run: cat README.md




    build_job:
        runs-on:  windows-latest
        steps:
            - name: display hello
              run: echo hello
    deploy_job:
        runs-on:  macos-latest
        steps:
            - run: echo hellow mac



